# Generated by Django 4.2.15 on 2024-08-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('faculty', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA')], max_length=10)),
            ],
        ),
    ]
